# - This code was generated by Shisho Cloud's internal system (protoc-gen-regolib).
# - When you find something to improve, you can create an GitHub issue, instead of creating pull requests.

package shisho.decision.aws.cloudtrail

import data.shisho
import data.shisho.assertion
import data.shisho.primitive

import future.keywords.every

# @title Ensure CloudTrail log file validation is enabled
# You can emit this decision as follows:
# 
# ```
# import data.shisho
# 
# decisions[d] {
#   # the resource ID to review (e.g. a GitHub repository, etc.)
#   subject := "test"
#
#   # whether the target is allowed by this policy or not
#   allowed := true
#
#   d := shisho.decision.aws.cloudtrail.log_file_validation({
#     "allowed": allowed,
#     "subject": subject,
#     "payload": shisho.decision.aws.cloudtrail.log_file_validation_payload({
#       "enabled": false,
#     }),
#   })
# }
# ```

# METADATA
# title: "decision.api.shisho.dev/v1beta:aws_cloudtrail_log_file_validation"
# scope: "rule"
# description: |
#   Emits a decision whose type is decision.api.shisho.dev/v1beta:aws_cloudtrail_log_file_validation".
log_file_validation(d) = x {
	shisho.decision.has_required_fields(d)
	x := {
		"header": log_file_validation_header({
			"allowed": d.allowed,
			"subject": d.subject,
			"locator": log_file_validation_locator(d),
			"severity": log_file_validation_severity(d),
		}),
		"payload": d.payload,
	}
}

log_file_validation_severity(d) := shisho.decision.severity_info {
	d.allowed == true
} else := d.severity {
	not is_null(d.severity)
} else := 2

log_file_validation_locator(d) := d.locator {
	not is_null(d.locator)
} else := ""

log_file_validation_kind = "aws_cloudtrail_log_file_validation"

log_file_validation_header(h) = x {
	x := {
		"api_version": "decision.api.shisho.dev/v1beta",
		"kind": log_file_validation_kind,
		"subject": h.subject,
		"locator": h.locator,
		"severity": h.severity,
		"labels": {},
		"annotations": {
			"decision.api.shisho.dev:aws/cis-benchmark/v1.5.0": "3.2",
			"decision.api.shisho.dev:needs-manual-review": "false",
			"decision.api.shisho.dev:ssc/category": "infrastructure",
		},
		"type": shisho.decision.as_decision_type(log_file_validation_allowed(h)),
	}
}

# Force to allow the given decision following resource exception policy
log_file_validation_allowed(h) {
	data.params != null
	data.params.resource_exceptions != null
	shisho.resource.is_excepted(data.params.resource_exceptions, h.subject)
} else := h.allowed

# METADATA
# title: "Entry of decision.api.shisho.dev/v1beta:aws_cloudtrail_log_file_validation"
# scope: "rule"
# description: |
#   Emits a decision entry describing the detail of a decision decision.api.shisho.dev/v1beta:aws_cloudtrail_log_file_validation
#
#   The parameter `data` is an object with the following fields: 
#   - enabled: boolean
#
#   For instance, `data` can take the following value:
#   ```rego
#   {
#     "enabled": false,
#   }
#   ```
log_file_validation_payload(edata) := x {
	log_file_validation_payload_assert(edata, "<the argument to log_file_validation_payload>")
	x := json.marshal(edata)
} else := ""

log_file_validation_payload_assert(edata, hint) {
	assertion.is_type(edata, "object", hint)

	key_checks := [assertion.has_key(edata, "enabled", concat("", [hint, ".", "enabled"]))]
	every c in key_checks { c }

	value_checks := [log_file_validation_payload_assert_enabled(edata, "enabled", concat("", [hint, ".", "enabled"]))]
	every c in value_checks { c }
} else := false

log_file_validation_payload_assert_enabled(x, key, hint) {
	assertion.is_type(x[key], "boolean", hint)
} else := false
