# - This code was generated by Shisho Cloud's internal system (protoc-gen-regolib).
# - When you find something to improve, you can create an GitHub issue, instead of creating pull requests.

package shisho.decision.aws.networking

import data.shisho
import data.shisho.assertion
import data.shisho.primitive

import future.keywords.every

# @title Ensure that Transit Gateways do not automatically accept VPC attachment requests
# You can emit this decision as follows:
#
# ```
# import data.shisho
#
# decisions[d] {
#   # the resource ID to review (e.g. a GitHub repository, etc.)
#   subject := "test"
#
#   # whether the target is allowed by this policy or not
#   allowed := true
#
#   d := shisho.decision.aws.networking.transit_gateway_auto_vpc_attachment({
#     "allowed": allowed,
#     "subject": subject,
#     "payload": shisho.decision.aws.networking.transit_gateway_auto_vpc_attachment_payload({
#       "auto_accept_shared_attachments_disabled": false,
#     }),
#   })
# }
# ```

# METADATA
# title: "decision.api.shisho.dev/v1beta:aws_networking_transit_gateway_auto_vpc_attachment"
# scope: "rule"
# description: |
#   Emits a decision whose type is decision.api.shisho.dev/v1beta:aws_networking_transit_gateway_auto_vpc_attachment".
transit_gateway_auto_vpc_attachment(d) = x {
	shisho.decision.has_required_fields(d)
	x := {
		"header": transit_gateway_auto_vpc_attachment_header({
			"allowed": d.allowed,
			"subject": d.subject,
			"locator": transit_gateway_auto_vpc_attachment_locator(d),
			"severity": transit_gateway_auto_vpc_attachment_severity(d),
		}),
		"payload": d.payload,
	}
}

transit_gateway_auto_vpc_attachment_severity(d) := shisho.decision.severity_info {
	d.allowed == true
} else := d.severity {
	not is_null(d.severity)
} else := 2

transit_gateway_auto_vpc_attachment_locator(d) := d.locator {
	not is_null(d.locator)
} else := ""

transit_gateway_auto_vpc_attachment_kind = "aws_networking_transit_gateway_auto_vpc_attachment"

transit_gateway_auto_vpc_attachment_header(h) = x {
	x := {
		"api_version": "decision.api.shisho.dev/v1beta",
		"kind": transit_gateway_auto_vpc_attachment_kind,
		"subject": h.subject,
		"locator": h.locator,
		"severity": h.severity,
		"labels": {},
		"annotations": {
			"decision.api.shisho.dev:aws/fsbp/latest": "EC2.23",
			"decision.api.shisho.dev:needs-manual-review": "false",
			"decision.api.shisho.dev:ssc/category": "infrastructure",
		},
		"type": shisho.decision.as_decision_type(transit_gateway_auto_vpc_attachment_allowed(h)),
	}
}

# Force to allow the given decision following resource exception policy
transit_gateway_auto_vpc_attachment_allowed(h) {
	data.params != null
	data.params.resource_exceptions != null
	shisho.resource.is_excepted(data.params.resource_exceptions, h.subject)
} else := h.allowed

# METADATA
# title: "Entry of decision.api.shisho.dev/v1beta:aws_networking_transit_gateway_auto_vpc_attachment"
# scope: "rule"
# description: |
#   Emits a decision entry describing the detail of a decision decision.api.shisho.dev/v1beta:aws_networking_transit_gateway_auto_vpc_attachment
#
#   The parameter `data` is an object with the following fields:
#   - auto_accept_shared_attachments_disabled: boolean
#
#   For instance, `data` can take the following value:
#   ```rego
#   {
#     "auto_accept_shared_attachments_disabled": false,
#   }
#   ```
transit_gateway_auto_vpc_attachment_payload(edata) := x {
	transit_gateway_auto_vpc_attachment_payload_assert(edata, "<the argument to transit_gateway_auto_vpc_attachment_payload>")
	x := json.marshal(edata)
} else := ""

transit_gateway_auto_vpc_attachment_payload_assert(edata, hint) {
	assertion.is_type(edata, "object", hint)

	key_checks := [assertion.has_key(edata, "auto_accept_shared_attachments_disabled", concat("", [hint, ".", "auto_accept_shared_attachments_disabled"]))]
	every c in key_checks { c }

	value_checks := [transit_gateway_auto_vpc_attachment_payload_assert_auto_accept_shared_attachments_disabled(edata, "auto_accept_shared_attachments_disabled", concat("", [hint, ".", "auto_accept_shared_attachments_disabled"]))]
	every c in value_checks { c }
} else := false

transit_gateway_auto_vpc_attachment_payload_assert_auto_accept_shared_attachments_disabled(x, key, hint) {
	assertion.is_type(x[key], "boolean", hint)
} else := false
